manifest:
  version: 0.8

  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr 
      revision: main
      import:
        file: west.yml 
        path-prefix: deps 
        name-allowlist:
          - zephyr
          - cmsis
          - cmsis_6 
          - hal_nordic
          - mcuboot
          - zcbor
          - mbedtls 

  self:
    path: app
